#spring :
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url : jdbc:mysql://localhost:3306/bloomGroom?serverTimezone=Asia/Seoul
#    username: groom
#    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate.dialect: org.hibernate.dialect.MySQLDialect



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bloomgroom-db.c1c4044ywxxq.ap-northeast-2.rds.amazonaws.com:3306
    username: admin
    password: bloomgroom1
  jpa:
    hibernate:
      ddl-auto: create # create, update, validate, none
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true