spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bloomgroom-db.c1c4044ywxxq.ap-northeast-2.rds.amazonaws.com:3306
    username: admin
    password: bloomgroom1
  jpa:
    hibernate:
      ddl-auto: update # create, update, validate, none
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true